name: yola_yolov3_pepper_mmdet
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - jmespath==0.10.0
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pycocotools==2.0.7
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - requests==2.28.2
      - rich==13.4.2
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tomli==2.3.0
      - torch==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - tqdm==4.65.2
      - triton==2.1.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - yapf==0.43.0
      - zipp==3.20.2
